[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Msys2Root, [Parameter(Mandatory)][string]$SourceRoot,
    [Parameter(Mandatory)][string]$BuildRoot, [Parameter(Mandatory)][string]$Prefix,
    [Parameter(Mandatory)][string]$EvidenceRoot, [Parameter(Mandatory)][string]$ToolchainEvidencePath,
    [Parameter(Mandatory)][string]$SourceEvidencePath, [string]$ManifestRoot
)
$ErrorActionPreference='Stop'
function Test-AbsolutePath([string]$Path){return -not [string]::IsNullOrWhiteSpace($Path)-and [IO.Path]::GetFullPath($Path)-ceq $Path}
function Read-Json([string]$Path){try{Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json}catch{throw "Invalid provenance evidence JSON: $Path"}}
if([string]::IsNullOrWhiteSpace($ManifestRoot)){$ManifestRoot=Join-Path(Split-Path -Parent $PSScriptRoot)'manifests'}
$manifestRoot=[IO.Path]::GetFullPath($ManifestRoot);&(Join-Path $PSScriptRoot 'Test-NativeLock.ps1')-ManifestRoot $manifestRoot -BuildInputsOnly|Out-Null
foreach($pair in @(@{name='MSYS2 root';path=$Msys2Root},@{name='source root';path=$SourceRoot},@{name='build root';path=$BuildRoot},@{name='prefix';path=$Prefix},@{name='evidence root';path=$EvidenceRoot})){if(-not(Test-AbsolutePath([string]$pair.path))){throw "$($pair.name) must be absolute."}}
$msys=[IO.Path]::GetFullPath($Msys2Root);$sources=[IO.Path]::GetFullPath($SourceRoot);$build=[IO.Path]::GetFullPath($BuildRoot);$prefix=[IO.Path]::GetFullPath($Prefix);$evidence=[IO.Path]::GetFullPath($EvidenceRoot)
foreach($path in @($build,$prefix,$evidence)){if(Test-Path -LiteralPath $path){throw 'Build, prefix, and evidence directories must be new clean locations.'}}
$toolEvidence=Read-Json $ToolchainEvidencePath;$sourceEvidence=Read-Json $SourceEvidencePath
if($toolEvidence.kind-cne'hvp-native-toolchain-install-evidence'-or[IO.Path]::GetFullPath([string]$toolEvidence.installDirectory)-cne$msys-or$sourceEvidence.kind-cne'hvp-native-source-tree-evidence'-or[IO.Path]::GetFullPath([string]$sourceEvidence.sourceDirectory)-cne$sources){throw 'Build roots are not bound to the supplied install/extraction evidence.'}
$toolLock=Join-Path $manifestRoot 'toolchain.lock.json';$sourceLock=Join-Path $manifestRoot 'native-inputs.json'
if((Get-FileHash -LiteralPath $toolLock -Algorithm SHA256).Hash.ToLowerInvariant()-cne$toolEvidence.toolchainLockSha256-or(Get-FileHash -LiteralPath $sourceLock -Algorithm SHA256).Hash.ToLowerInvariant()-cne$sourceEvidence.sourceLockSha256){throw 'Build provenance evidence does not bind the current locks.'}
if((&(Join-Path $PSScriptRoot 'Get-NativeTreeHash.ps1')-Root $msys).sha256-cne$toolEvidence.treeSha256-or(&(Join-Path $PSScriptRoot 'Get-NativeTreeHash.ps1')-Root $sources).sha256-cne$sourceEvidence.treeSha256){throw 'Toolchain or source tree changed after validated installation/extraction.'}
foreach($id in @('mpv','ffmpeg','libplacebo','libass','spirv-cross','glslang','fast-float','freetype','fribidi','harfbuzz','zlib','jinja','markupsafe')){if(-not(Test-Path -LiteralPath(Join-Path $sources $id)-PathType Container)){throw "Validated source directory is missing: $id"}}
$bash=Join-Path $msys 'usr/bin/bash.exe';$cygpath=Join-Path $msys 'usr/bin/cygpath.exe';$script=Join-Path(Split-Path -Parent $PSScriptRoot)'config/build-native.sh'
foreach($file in @($bash,$cygpath,$script,(Join-Path $msys 'clang64/bin/clang.exe'))){if(-not(Test-Path -LiteralPath $file -PathType Leaf)){throw "Pinned build executable/script is missing: $file"}}
function To-MsysPath([string]$Path){$result=@(&$cygpath -u([IO.Path]::GetFullPath($Path)));if($LASTEXITCODE-ne 0-or$result.Count-ne 1){throw "cygpath failed for: $Path"};return[string]$result[0]}
New-Item -ItemType Directory -Path $build,$prefix,$evidence|Out-Null
$previous=@{};foreach($name in @('MSYS2_ROOT','SOURCE_ROOT','BUILD_ROOT','PREFIX','EVIDENCE_ROOT')){$previous[$name]=[Environment]::GetEnvironmentVariable($name,'Process')}
try{$env:MSYS2_ROOT=To-MsysPath $msys;$env:SOURCE_ROOT=To-MsysPath $sources;$env:BUILD_ROOT=To-MsysPath $build;$env:PREFIX=To-MsysPath $prefix;$env:EVIDENCE_ROOT=To-MsysPath $evidence;&(Join-Path $PSScriptRoot 'Initialize-NativeReproducibilityEnvironment.ps1')|Out-Null;&$bash --noprofile --norc(To-MsysPath $script);if($LASTEXITCODE-ne 0){throw 'Pinned native build failed.'}}finally{foreach($name in $previous.Keys){[Environment]::SetEnvironmentVariable($name,$previous[$name],'Process')}}
$policy=Read-Json(Join-Path $manifestRoot 'native-policy.json');$requested=[ordered]@{schemaVersion=1;kind='hvp-native-requested-configuration';policySha256=(Get-FileHash -LiteralPath(Join-Path $manifestRoot 'native-policy.json')-Algorithm SHA256).Hash.ToLowerInvariant();components=$policy.required}
[IO.File]::WriteAllText((Join-Path $evidence 'requested-configuration.json'),(($requested|ConvertTo-Json -Depth 12)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))
$compiled=@();$dependencies=@();foreach($file in @(Get-ChildItem -LiteralPath $evidence -File -Force)){if($file.Name-like'*compiled*'-or$file.Name-like'*compile-commands*'){$compiled+=[ordered]@{path=$file.Name;sha256=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}};if($file.Name-like'*dependencies*'-or$file.Name-like'*CMakeCache*'-or$file.Name-eq'ffmpeg-config.mak'){$dependencies+=[ordered]@{path=$file.Name;sha256=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}}}
if($compiled.Count-lt 10-or$dependencies.Count-lt 10){throw 'Native build did not capture the complete compiled-source/dependency evidence set.'}
[IO.File]::WriteAllText((Join-Path $evidence 'compiled-sources.json'),(([ordered]@{schemaVersion=1;kind='hvp-native-compiled-source-evidence';files=$compiled}|ConvertTo-Json -Depth 6)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $evidence 'dependency-paths.json'),(([ordered]@{schemaVersion=1;kind='hvp-native-dependency-path-evidence';files=$dependencies;privatePrefix=$prefix}|ConvertTo-Json -Depth 6)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))
&(Join-Path $PSScriptRoot 'Test-NativeDependencyIsolation.ps1')-EvidenceRoot $evidence -Prefix $prefix -SourceRoot $sources -BuildRoot $build -Msys2Root $msys -OutputPath(Join-Path $evidence 'dependency-isolation.json')|Out-Null
$toolFiles=@('clang64/bin/clang.exe','clang64/bin/lld.exe','clang64/bin/cmake.exe','clang64/bin/ninja.exe','clang64/bin/python.exe','usr/bin/bash.exe','usr/bin/make.exe');$tools=@();foreach($relative in $toolFiles){$path=Join-Path $msys $relative;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Pinned tool is missing after build: $relative"};$tools+=[ordered]@{path=$relative;sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}}
[IO.File]::WriteAllText((Join-Path $evidence 'tool-identities.json'),(([ordered]@{schemaVersion=1;kind='hvp-native-tool-identities';tools=$tools}|ConvertTo-Json -Depth 6)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))
$compiler=Join-Path $msys 'clang64/bin/clang.exe';$linker=Join-Path $msys 'clang64/bin/lld.exe';$effectiveComponents=@()
$evidenceMap=@{
 'mpv'=@("meson-introspection=$(Join-Path $evidence 'mpv-buildoptions.json')","dependency-paths=$(Join-Path $evidence 'mpv-dependencies.json')","compiled-source-list=$(Join-Path $evidence 'mpv-compiled-objects.txt')");
 'ffmpeg'=@("ffmpeg-config=$(Join-Path $evidence 'ffmpeg-config.mak')","dependency-paths=$(Join-Path $evidence 'ffmpeg-config.mak')","compiled-source-list=$(Join-Path $evidence 'ffmpeg-compiled-objects.txt')");
 'libplacebo'=@("meson-introspection=$(Join-Path $evidence 'libplacebo-buildoptions.json')","dependency-paths=$(Join-Path $evidence 'libplacebo-dependencies.json')","compiled-source-list=$(Join-Path $evidence 'libplacebo-compiled-objects.txt')");
 'libass'=@("meson-introspection=$(Join-Path $evidence 'libass-buildoptions.json')","dependency-paths=$(Join-Path $evidence 'libass-dependencies.json')","compiled-source-list=$(Join-Path $evidence 'libass-compiled-objects.txt')");
 'spirv-cross'=@("cmake-cache=$(Join-Path $evidence 'spirv-cross-CMakeCache.txt')","dependency-paths=$(Join-Path $evidence 'spirv-cross-CMakeCache.txt')","compiled-source-list=$(Join-Path $evidence 'spirv-cross-compiled-objects.txt')");
 'glslang'=@("cmake-cache=$(Join-Path $evidence 'glslang-CMakeCache.txt')","dependency-paths=$(Join-Path $evidence 'glslang-CMakeCache.txt')","compiled-source-list=$(Join-Path $evidence 'glslang-compiled-objects.txt')");
 'freetype'=@("meson-introspection=$(Join-Path $evidence 'freetype-buildoptions.json')","dependency-paths=$(Join-Path $evidence 'freetype-dependencies.json')","compiled-source-list=$(Join-Path $evidence 'freetype-compiled-objects.txt')");
 'fribidi'=@("meson-introspection=$(Join-Path $evidence 'fribidi-buildoptions.json')","dependency-paths=$(Join-Path $evidence 'fribidi-dependencies.json')","compiled-source-list=$(Join-Path $evidence 'fribidi-compiled-objects.txt')");
 'harfbuzz'=@("meson-introspection=$(Join-Path $evidence 'harfbuzz-buildoptions.json')","dependency-paths=$(Join-Path $evidence 'harfbuzz-dependencies.json')","compiled-source-list=$(Join-Path $evidence 'harfbuzz-compiled-objects.txt')");
 'zlib'=@("cmake-cache=$(Join-Path $evidence 'zlib-CMakeCache.txt')","dependency-paths=$(Join-Path $evidence 'zlib-CMakeCache.txt')","compiled-source-list=$(Join-Path $evidence 'zlib-compiled-objects.txt')")
}
foreach($component in $evidenceMap.Keys){$path=Join-Path $evidence "$component-effective.json";&(Join-Path $PSScriptRoot 'Save-NativeEffectiveConfiguration.ps1')-OutputPath $path -Component $component -RequestedFlags @($policy.required.$component) -Evidence @($evidenceMap[$component]) -CompilerPath $compiler -LinkerPath $linker -PolicyPath(Join-Path $manifestRoot 'native-policy.json')|Out-Null;$effectiveComponents+=[ordered]@{component=$component;path=[IO.Path]::GetFileName($path);sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}}
$effective=[ordered]@{schemaVersion=1;kind='hvp-native-effective-configuration';gpuNextCompiled=$true;d3d11ContextCompiled=$true;d3d11vaCompiled=$true;components=$effectiveComponents};[IO.File]::WriteAllText((Join-Path $evidence 'effective-configuration.json'),(($effective|ConvertTo-Json -Depth 8)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))
[pscustomobject]@{buildRoot=$build;prefix=$prefix;evidenceRoot=$evidence;repositorySync=$false;wrapMode='nofallback';targetSearch='private prefix only'}
