[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ClientHeaderPath,
    [Parameter(Mandatory)][string]$OutputPath,
    [Parameter(Mandatory)][ValidatePattern('^[0-9a-fA-F]{64}$')][string]$ExpectedHeaderSha256
)

$ErrorActionPreference = 'Stop'
$header = [IO.Path]::GetFullPath($ClientHeaderPath)
if (-not [IO.File]::Exists($header)) { throw "Pinned mpv client header does not exist: $header" }
$hash = (Get-FileHash -LiteralPath $header -Algorithm SHA256).Hash.ToLowerInvariant()
if ($hash -cne $ExpectedHeaderSha256.ToLowerInvariant()) { throw 'The supplied client header does not match its pinned SHA-256.' }
$text = [IO.File]::ReadAllText($header)
if ($text -notmatch '(?s)#\s*define\s+MPV_CLIENT_API_VERSION\s+MPV_MAKE_VERSION\s*\(\s*(?<major>\d+)\s*,\s*(?<minor>\d+)\s*\)') { throw 'Could not read MPV_CLIENT_API_VERSION from the pinned client header.' }
$major = [int]$Matches.major; $minor = [int]$Matches.minor
if ($major -ne 2 -or $minor -lt 5) { throw "Pinned client header API $major.$minor is not compatible with HVP's required API 2.5." }
foreach ($symbol in @('mpv_client_api_version','mpv_create','mpv_initialize','mpv_terminate_destroy','mpv_set_option_string','mpv_command')) {
    if ($text -notmatch "(?m)\b$symbol\s*\(") { throw "Pinned client header is missing required declaration: $symbol" }
}
$generated = @"
// <auto-generated />
// Generated from mpv/include/mpv/client.h SHA-256: $hash
// This file intentionally represents only the Phase 0 smoke ABI surface.
using System;
using System.Runtime.InteropServices;

namespace Hvp.Playback.Interop;

internal static class LibmpvNativeGenerated
{
    internal const uint ClientApiMajor = $major;
    internal const uint ClientApiMinor = $minor;
    // mpv_handle* and char** are pointer-width values: IntPtr on Windows x64.
    // Windows LLP64 makes C unsigned long 32 bits.
    [DllImport("libmpv-2.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)] internal static extern uint mpv_client_api_version();
    [DllImport("libmpv-2.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)] internal static extern IntPtr mpv_create();
    [DllImport("libmpv-2.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)] internal static extern int mpv_initialize(IntPtr handle);
    [DllImport("libmpv-2.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)] internal static extern void mpv_terminate_destroy(IntPtr handle);
    [DllImport("libmpv-2.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)] internal static extern int mpv_set_option_string(IntPtr handle, [MarshalAs(UnmanagedType.LPUTF8Str)] string name, [MarshalAs(UnmanagedType.LPUTF8Str)] string value);
    [DllImport("libmpv-2.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)] internal static extern int mpv_command(IntPtr handle, IntPtr args);
}
"@
$destination = [IO.Path]::GetFullPath($OutputPath)
$parent = Split-Path -Parent $destination
if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
[IO.File]::WriteAllText($destination, $generated.Replace("`r`n", "`n"), [Text.UTF8Encoding]::new($false))
[pscustomobject]@{ header = $header; sha256 = $hash; apiVersion = "$major.$minor"; output = $destination }
